### ISSUE TITLE
Learning GitHub

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#103]
- [ ] Branches: merge vs rebase
- [ ] [Search - date based github issue "created:2017-02-01..2017-02-08"](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3Ajanzeteachesit+created%3A2017-02-01..2017-02-08+)
- [ ]  ProTip! What’s not been updated in a month: updated:<2017-02-22.
- [ ]  ProTip! no:label
- [ ]  ProTip! Type g i on any issue or pull request to go back to the issue listing page.
- [ ] ProTip! no:milestone will show everything without a milestone.
- [ ] ProTip! Updated in the last three days: updated:>2017-03-19.

Refernces:
- [tiimgreen/github-cheat-sheet](https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md)
- [using-search-to-filter-issues-and-pull-requests/](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/)
- [search-syntax](https://help.github.com/articles/search-syntax/)
- [searching-issues](https://help.github.com/articles/searching-issues/)

**Comment by janzeteachesit** [comment]
https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md

**Comment by janzeteachesit** [comment]
#231
