### ISSUE TITLE
100 Days of Writing Published and Drafts

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#104]
# Drafts and Published TOC
- [x] create/copy _drafts list to GitBook
- [ ] update drafts to reflect current
- [ ] cross link new writing
- [x] link to [100-days-writing_drafts](https://github.com/janzeteachesit/100-days-of-writing/tree/master/_drafts)
- [x] link to [writing template](https://github.com/janzeteachesit/100-days-of-writing/blob/master/docs/template.md)

**Comment by janzeteachesit** [comment]
## Drafts #86 _drafts in [100 Days](https://github.com/janzeteachesit/100-days-of-writing/tree/master/_drafts)

title|issue|description|status
----|------|------------|------
Template | #104 | [writing template](https://github.com/janzeteachesit/100-days-of-writing/blob/master/docs/template.md) | Open
_ | _ | [_drafts/stem8-projects.md](https://github.com/janzeteachesit/100-days-of-writing/tree/master/_drafts)|open
_ |#68| [_drafts/deeper-learning.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/deeper-learning.md)|open  
_ | _ | [_drafts/mastery-in-class.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/mastery-in-class.md)|open
_ | #184 | [_drafts/painting-with-water-first.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/painting-with-water-first.md)|closed 
_ | janzeteachesit/100-days-of-writing#24 |  [_drafts/powerful-ideas-statistical-mechanics.md](https://github.com/janzeteachesit/100-days-of-writing/edit/master/_drafts/powerful-ideas-statistical-mechanics.md)| _
_ | _ |[_drafts/domains-with-abundant-materials-or-sparse-materials.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/domains-with-abundant-materials-or-sparse-materials.md)|
_ | _ | [_drafts/005-letter-to-parents.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/005-letter-to-parents.md) | _
_ | _ | [_drafts/004-communicating-student-learning-day-2]( https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/004-communicating-student-learning-day-2) | _
_ | _ | [_drafts/what-is-my-purpose.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/what-is-my-purpose.md) | _
_ | _ | [_drafts/serenity-prayer-for-teachers.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/serenity-prayer-for-teachers.md) | _
_ | _ | [_drafts/outline](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/outline) | _
_ | _ | [_drafts/mastery-in-class.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/mastery-in-class.md) | _
_ | _ | [_drafts/everfi-financial-micro-credential.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/everfi-financial-micro-credential.md) | _
_ | _ | [_drafts/driving-learning-in-the-resume-project.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/driving-learning-in-the-resume-project.md) | _
_ | _ | [_drafts/20162017-elementary-inquiry.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/20162017-elementary-inquiry.md) | _
_ | _ | [_drafts/100daysofcode001.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/100daysofcode001.md) | _
_ | _ | [_drafts/015-agile-and-github-milestones.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/015-agile-and-github-milestones.md) | _
_ | _ | [_drafts/014-mindfulness.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/014-mindfulness.md) | _
_ | _ | [_drafts/013-brave-new-world.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/013-brave-new-world.md) | _
_ | _ | [_drafts/012-pgau-nineteen-eighty-four.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/012-pgau-nineteen-eighty-four.md) | _
_ | _ | [_drafts/011-hill-climbing.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/011-hill-climbing.md) | _
_ | _ | [_drafts/010-diversity%20in%20groups.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/010-diversity%20in%20groups.md) | _
_ | _ | [_drafts/009-halfway-summary.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/009-halfway-summary.md) | _
_ | _ | [_drafts/008-inquiry-first%20meeting.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/008-inquiry-first%20meeting.md) | _
_ | _ | [_drafts/007-STEM-mapping-disease.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/007-STEM-mapping-disease.md) | _
_ | _ | [_drafts/006-characteristics-stem-student.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/006-characteristics-stem-student.md) | _

**Comment by janzeteachesit** [comment]
## [link to table of published articles](https://github.com/janzeteachesit/100-days-of-writing/blob/master/docs/tally.md)

## Un-linked Articles
- #8 Article: My Public Self - busterbenson
- #15 Article: Bullshit Detector - Being Less Wrong <= all contents; closed / re-open when writing about.
    - [ ] [Bullshit Detector! A Guide to Being Less Wrong](https://betterhumans.coach.me/bullshit-detector-a-guide-to-being-less-wrong-ce0bbbd1a41b#.5lvfxur01)
    - [ ] reread & comment/write
    - [ ] cards for study?
- #141 Article: Different Approach to Teaching Kids and Teens to Code <= all contents; closed / re-open when writing about.
    - [ ] [A Different Approach to Teaching Kids and Teens to Code](https://medium.com/@alishah.novin/a-different-approach-to-teaching-kids-and-teens-to-code-43b7192644c9#.cus067vmd)

## End-Notes. Links, Errata
[_drafts/deeper-learning.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/deeper-learning.md)
#68 #184 #188

**Comment by janzeteachesit** [comment]
[_drafts/deeper-learning.m](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/deeper-learning.md)
#68

**Comment by janzeteachesit** [comment]
[_drafts/deeper-learning.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/deeper-learning.md)
#68 #184 #188
