### ISSUE TITLE
Status Update format

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#132]
- [x] create wording of statements
- [x] adjust for different classes
- [ ] longer term - doc/form?
- [ ] link to longer description of goals
- [ ] rubric/points?

**Comment by janzeteachesit** [comment]
## 20170220 GClass links
- [GDA](https://classroom.google.com/u/0/c/MjE2MTczODc3OVpa/sa/NDYyNzY0NjY2OFpa/details)
- [GR](https://classroom.google.com/u/0/c/MjE2MjAyMjU4OFpa/sa/NDYyODEwNTg2MFpa/details)
- [CSP](https://classroom.google.com/u/0/c/MjE2MTg1MTAwOVpa/sa/NDYyODA3NTM3Nlpa/details)
- [I2CS](https://classroom.google.com/u/0/c/MjE2MjE1OTE0MVpa/sa/NDYyODA3NTM3M1pa/details)

**Comment by janzeteachesit** [comment]
[GForm](https://docs.google.com/a/templeton.vsb.bc.ca/forms/d/1BGW68dxZU6FKn0uNRpDUW0Rc1vGpr09BcIzRQ73cWYY/edit?usp=sharing)
