### ISSUE TITLE
CSL Doc

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#133]
# Communicating Student Learning
[csl.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/in-progress/csl.md) | [CSL Doc #133](https://github.com/janzeteachesit/Learning-Diary/issues/133)

20170321
- [ ] [csl-core-competencies.md](https://github.com/janzeteachesit/100-days-of-writing/blob/master/_drafts/csl-core-competencies.md)
- [ ] #269 Time Never on you Side
- [ ] #270 RAT
- [ ] #286 CSL Session Followup
- [Communicating Student Learning Handbook.docx](https://vsbworld-my.sharepoint.com/personal/cjanze_vsb_bc_ca/Documents/STEM/Communicating%20Student%20Learning%20Handbook.docx?d=w9251d41cd5bc42e48c08134c84ac5e85)

to get mastery:
show me mastery of the theory you are trying to apply and the tool you are using to apply.

have you mastered the theory behind what doing and the tool using to do it?
- [ ] connect to Core Competencies
- [ ] reflect on sessions so far - .md
- [ ] add to writing #188 
- [ ] add to ELEM #164

**Comment by janzeteachesit** [comment]
#155

**Comment by janzeteachesit** [comment]
to get mastery:
show me mastery of the theory you are trying to apply and the tool you are using to apply.

have you mastered the theory behind what doing and the tool using to do it?
