### ISSUE TITLE
ADST Issues Master List

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#163]
- [ ] CS in Algebra course outline/diary 
- [ ] S1B - [CSinALG - GitHub Project](https://github.com/janzeteachesit/Learning-Diary/projects/4)
- [ ] S1B #9 check names 
- [ ] [Computer Science in Algebra: Course A and B - Design Recipes - GDoc](https://docs.google.com/document/d/1Lw9fdM6bR7F-G-cTobw9rl-8S05JgKCKyed_tBSXoOc/edit?usp=sharing)
  - [x] created
  - [ ] checked

**Comment by janzeteachesit** [comment]
#153
