### ISSUE TITLE
TSSM - IRLY

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#251]
- updates
  - [ ] montlhy stuggles rename - add yearmonth, change summary, images
  - [ ] blaine things - add \#, yearmonth, change summary, images
  - [ ] movies - move yearmonth, change summary, images
  - [ ] active4life - add yearmonth, change summary, images
  - [ ] check author, full date, period
  - [ ] check first lines
- [Medium TSSM list - GitHub](https://github.com/templetontitan/tssm-v01/blob/master/src/medium_tssm.md)
- [SUMMARY.md - GitHub](https://github.com/templetontitan/tssm-v01/blob/master/SUMMARY.md)
- [all.css - GitHub](https://github.com/templetontitan/tssm-v01/blob/master/styles/all.css)
- [tssm.v01 - GitHub](https://github.com/templetontitan/tssm-v01)
- [citation.md - GitHub](https://github.com/templetontitan/tssm-v01/blob/master/assets/citation.md)
- [Templeton Secondary Student Magazine: Introduction - GItBook](https://tssm.gitbooks.io/tssm-vol-01/content/)
- [TSSM Vol 01 - GitBook](https://www.gitbook.com/book/tssm/tssm-vol-01/details)
- [template.md - GitHub](https://github.com/templetontitan/tssm-v01/blob/master/template.md)
