### ISSUE TITLE
STEM - 3D papercraft builds

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/Learning-Diary#299]
- paper triangles
- build a house
- strongest house/shape
- scale model building
- school
- room
- math - projecting amount of paper, tracking usage of materials

**Comment by janzeteachesit** [comment]
- http://babbledabbledo.com/stem-kids-straw-geodesic-dome/
- http://babbledabbledo.com/engineering-for-kids-skewer-structures/
- Make:  Tinkering [GDrive Search](https://drive.google.com/drive/u/0/search?q=tinkering)
- [Engineering for Every Kid - Janice VanCleave](http://www.arvindguptatoys.com/arvindgupta/engineering-janice.pdf)
- [Boston Museum of Science - ed search](site:www.mos.org/sites/dev-elvis.mos.org/files/docs/education/)
- [Earthquake Engineering for Out-of-School Time - Engineering Adventures](https://engineering.jhu.edu/sabes/wp-content/uploads/sites/28/2015/07/Shake-Things-Up-Educators-Guide-2014.pdf)
- tensegrity, cable stay
- [paper bridge with one piece of paper - GSearch](https://www.google.ca/search?rlz=1C1CHBF_enCA700CA700&espv=2&biw=1680&bih=905&q=paper+bridge+with+one+piece+of+paper&sa=X&ved=0ahUKEwjIhfSAsu7SAhVJ5GMKHc1uBucQ1QIITCgH)
- [Physics 26 How Strong Is a Paper Bridge?](http://www.karengoatkeeper.com/2016/physics-26-moving-forces/)
- [karengoatkeeper.com/tag/physics/](http://www.karengoatkeeper.com/tag/physics/)
- [paper bridge challenge solution - GSearch](https://www.google.ca/search?rlz=1C1CHBF_enCA700CA700&espv=2&biw=1680&bih=905&q=paper+bridge+challenge+solution&sa=X&ved=0ahUKEwjIhfSAsu7SAhVJ5GMKHc1uBucQ1QIISigF#q=paper+bridge+challenge+solution&tbs=qdr:y&*)
- [Paper Bridges: A civil engineering project from Science Buddies - S.A.](https://www.scientificamerican.com/article/paper-bridges)
- [Feel the Forces of a Suspension Bridge - S.A.](https://www.scientificamerican.com/article/bring-science-home-suspension-bridge/)
- http://www.sciencekids.co.nz/sciencefacts/engineering/bridges.html
- [index card bridge experiment - GSearch](https://www.google.ca/search?rlz=1C1CHBF_enCA700CA700&espv=2&biw=1680&bih=905&q=index+card+bridge+experiment&sa=X&ved=0ahUKEwjIhfSAsu7SAhVJ5GMKHc1uBucQ1QIISygG)

**Comment by janzeteachesit** [comment]
As Part of Engineering Instant Challenge / Learning Portfolio / Design Journal
 - http://keithms.blogspot.ca/2013/12/project-two.html
 - https://sites.google.com/a/student.mcsin-k12.org/nick/9thgrade
- http://iedvanguard.weebly.com/instant-challenge-paper-bridge.html

**Comment by janzeteachesit** [comment]
- [ ] Science Fair - own issue
  - http://www.sciencebuddies.org/science-fair-projects/project_guide_index.shtml?from=Blog
- [ ] [cre8iowa Instant Challenges](http://www.cre8iowa.org/resources/instant-challenge-library/)
- [ ] [chibitronics](https://chibitronics.com/teach/) - Welcome to our educational resources page for Chibitronics Circuit Stickers. Here you’ll find lesson plans, templates and fun activities for teachers, educators and students.
- http://fractalfoundation.org/resources/fractivities/
- https://www.wikiwand.com/en/Sonobe
- https://mathcraft.wonderhowto.com/how-to/make-hyperbolic-paraboloid-using-skewers-0131751/
- ribbed hemicube
- http://oceananinchdeep.blogspot.ca/2011/04/standardized-testing-and-reporting.html
- http://mathtourist.blogspot.ca/2015/11/folding-math.html
- https://sliceforms.wordpress.com/2010/11/21/a-sliceform-hyperbolic-paraboloid/
- https://sliceforms.wordpress.com/2010/04/16/templates-for-downloading/
- https://mathcraft.wonderhowto.com/how-to/create-concentric-circles-ellipses-cardioids-more-using-straight-lines-and-circle-0131356/
- https://scratch.mit.edu/projects/50076/#editor
- http://stringartandothers.deviantart.com/gallery/45129746/Digital-String-Art
- https://www.google.ca/webhp?sourceid=chrome-instant&rlz=1C1CHBF_enCA700CA700&ion=1&espv=2&ie=UTF-8#q=digital+string+art&*
- https://www.google.ca/search?q=string+art&rlz=1C1CHBF_enCA700CA700&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjH2_3slO7SAhVQ82MKHSdFBnsQ_AUICCgB&biw=1680&bih=905

**Comment by janzeteachesit** [comment]
https://drive.google.com/file/d/0BysMfTbvAUUVZDZzUXpXX3NURkE/view | Youth-Makerspace-Playbook_FINAL.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVYlJsb1U3bzNpNUU/view | cover.jpg - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVaTQxSlhST2ZDRDg/view | invent_to_learn_announcement.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVOXpncHQ3aXo5V0U/view | Getting Started with Ard 2ndEd - Arduino.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVaHkxUU8yQ2VMNVU/view | toy_take_apart_0.pdf - Google Drive
https://drive.google.com/file/d/0BxT7vWnQAXh4cjNCUmVTOEdWSEk/view | make_tinkering_2ndedition.pdf - Google Drive
https://drive.google.com/file/d/0BxT7vWnQAXh4ZDJoeG9PNy0xVWM/view | Tinkering - Curt Gabrielson - Make.pdf - Google Drive
https://docs.google.com/document/d/1GCRicyYgzKN0FVEATjh9-7AeqhImK-py5SIZ8pNhqhA/edit | Collaborative Tinkering Toolkit - Google Docs
https://docs.google.com/document/d/1cTrjwldBg972qyS2Axb_Hx9oB0o_LlRvsn-_X4ebQf8/edit | Fundamentals of Tinkering Materials List - Google Docs
https://drive.google.com/file/d/0BysMfTbvAUUVYTl0UTc3dlkyY0k/view | Invent To Learn Making in the Classroom.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVWDA0WGZaRUNEZVE/view | Tinker, Make & Learn Canvas Net - MOOC.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVWFdBOUdJdU1NWjg/view | Instructables.com - HYBRID CREA - Instructables.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVQTlFRGRhUExqRWc/view | Instructables.com - Powerful Tr - Instructables.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVaUltVGNMcmdhbW8/view | Instructables.com - Rube Goldbe - Instructables.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVMGhFeHFOck5ZN2M/view | Instructables.com - FUZZY SIPPE - Instructables.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVQU5tQlpPUHlHNkk/view | Instructables.com - Got Symmetr - Instructables.pdf - Google Drive
https://drive.google.com/file/d/0BysMfTbvAUUVUkk0elg1TmltV2s/view | Tinkering Fundamentals A Constr - Coursera.pdf - Google Drive
